#funciones
situ="Situación"
prefe="Preferencias"
inte="Intenciones"
editperf="Editar perfil"
fin="FIN"
mercredi="¡Al fin miércoles!\nSigue jugando para interactuar con nuevos perfiles y con aquellos que te han hecho dudar, o, si quieres desandar lo andado, haz Rerun y todo volverá a comenzar. Tal vez cambies de parecer...\n¡Tú decides!"
pcad="¡Game over! Después de 28 días sin jugar, tu perfil ha caducado"
seguir="Seguir jugando"
rerun="Rerun"
activar="ACTIVAR perfil"
desactivar="DESACTIVAR perfil"
dudas="¿¿¿DESACTIVAR perfil???"
polimenu="Polimatch"
jolin="¡Ups!"
nohay="Me temo que tendrás que esperar. Por el momento no hay perfiles disponibles para mostrarte"
continuar="Continuar..."
#código
estados={"alias":"Alias",
	"foto":"Foto",
	"situ":"Situación universitaria",
	"edad":"Edad","bio":"Sobre ti",
	"prefe":"Preferencias",
	"inte":"Intenciones"}
noname="Vaya. Parece que no tienes nombre de usuario de Telegram. Antes de continuar, crea uno para poder compartirlo y entrar en contacto con tus \"matches\""
ready="¡Tamo' ready!"
bienvenida="¡Hola! Te doy la bienvenida a UOMatchBot, el bot de Telegram que cambiará por completo tu experiencia social UniOvi.\nInteractuarás con perfiles de otros usuarios.\nLike, dislike, ¿tienes dudas?. Tú eliges.\n Conocer gente dentro de la Universidad de Oviedo ahora es mucho más sencillo y divertido que nunca.\n¿Jugamos?\n\nImportante. Si un perfil te parece inadecuado tendrás la opción de denunciarlo si lo consideras oportuno. Para cualquier otra incidencia que pueda surgir, siempre podrás contactar con los administradores a través de...(correo o comando)\n\nAntes de comenzar, deja que compruebe tu pertenencia a UniOvi a través de tu correo"
pidemail="Tu correo es:"
piiidemail="Debes introducir una dirección del tipo"# xxxxxx@uniovi.es
editmail_button="Cambiar dirección"
editmail="Tu nueva dirección de correo:"
pidealias="Elige un alias para tu perfil:"
piiidealias="Elige un alias para tu perfil:\n(entre 3 y 16 caracteres)"
editalias="Editar Alias:\n(entre 3 y 16 caracteres)"
pidefoto="Envía una foto bien hermosa para mostrar en tu perfil"
caca="Procesando imagen... (tanta belleza ralentiza lo' motore')"
pidesitu="Oye, ¿y tú qué haces en UniOvi? (facultad/estudios/curso/...):"
piiidesitu="Oye, ¿y tú qué haces en UniOvi?\n(entre 3 y 64 caracteres)"
editsitu="Editar Situación universitaria:\n(entre 3 y 64 caracteres)"
pideedad="¿Cuántos años tienes?"
piiideedad="¿Cuántos años tienes?\n(número entero entre 18 y 200)"
editedad="Editar Edad:\n(número entero entre 18 y 200)"
pidebio="Unas palabras sobre ti:"
piiidebio="Unas palabras sobre ti:\n(entre 16 y 320 caracteres)"
editbio="Editar Sobre ti:\n(entre 16 y 320 caracteres)"
pideprefe="¿Qué buscas?"
piiideprefe="¿Qué buscas?\n(entre 2 y 32 caracteres)"
editprefe="Editar Preferencias:\n(entre 2 y 32 caracteres)"
pideinte="¿Qué pretendes?"
piiideinte="¿Qué pretendes?\n(hasta 64 caracteres)"
editinte="Editar Intenciones:\n(hasta 64 caracteres)"
match="Buenas noticias. ¡Tienes un match!"
edit="Editar"
advertencia="Si desactivas el perfil, no podrás volver a activarlo hasta el próximo miércoles.\n¿Seguro que quieres continuar?"
enviado="Correo enviado a"
todobien="Si todo ha ido bien, habrás recibido un código que caducará dentro de"
minutos="minutos"
pidecodigo="Código recibido:"
mal="Error. Por favor, vuelve a intentarlo"
caducado="Lo siento, tu código ha caducado"
reenv="Reenviar código"
dentro="¡Estás dentro, colega! Vamos a crear tu perfil"
empezar="¡Aquí tienes tu perfil! Esto es lo que verán los demás. Date un like y...¡qué comience el juego!"
editarperfil="Recuerda, siempre podrás editar y/o desactivar tu perfil entrando al menú con el comando /perfil\nPuedes hacerlo ahora si lo crees conveniente..."
help="Esto es la ayuda..."
